---
root: true
env:
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended

  - airbnb-typescript/base
rules:
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/lines-between-class-members': off

  import/prefer-default-export: off
  import/no-cycle: off
  import/export: off

  class-methods-use-this: off
  consistent-return: off
  default-case: off
  lines-between-class-members: off
  no-await-in-loop: off
  no-console: off
  no-return-await: off
  no-redeclare: off

  no-restricted-syntax:
    - error
    - selector: ForInStatement
      message: 'for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array.'
    - selector: LabeledStatement
      message: 'Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand.'
    - selector: WithStatement
      message: '`with` is disallowed in strict mode because it makes code impossible to predict and optimize.'
